name: Matrix fail-fast

on: 
 workflow_dispatch

jobs: 
  matrix-jobs:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
       os:
       - ubuntu-latest
       - windows-latest
       java-version: [17, 21]
    steps:
         - name: Setup Java JDK
           uses: actions/setup-java@v3.14.1
           with:
             java-version: ${{matrix.java-version}}
             distribution: microsoft
