name: max-parallel

on: 
 workflow_dispatch

jobs: 
  matrix-jobs:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
       include: 
       - index: 0
         total: 4
         os: ubuntu-latest
         java-version: 17
         
       - index: 1
         total: 4
         os: ubuntu-latest
         java-version: 21
         
       - index: 2
         total: 4
         os: windows-latest
         java-version: 17 

       - index: 3
         total: 4
         os: windows-latest
         java-version: 21     
    steps:
         - name: Setup Java JDK
           uses: actions/setup-java@v3.14.1
           with:
             java-version: ${{matrix.java-version}}
             distribution: microsoft
