name: node js setup

on: 
  workflow_dispatch:

jobs:
  node-js:
   runs-on: ubuntu-latest
   steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 22
      - run: node -v     
          
    
