name: Output workflow

on: workflow_dispatch

jobs: 
 # outputs:
   gen-msg:
    runs-on: ubuntu-latest
    outputs: 
      message: ${{steps.set-message.outputs.greetings}}

    steps:
      - id: set-message
        run: |
         echo "greetings= Hello Welcome" >> $GITHUB_OUTPUT
         echo "01= Not Welcome" >> $GITHUB_OUTPUT

   dis-msg: 
     needs: gen-msg
     runs-on: ubuntu-latest
     steps:
       - run: echo 'needs.gen-msg.outputs.message'
