name: python setup

on: workflow_dispatch

jobs: 
  python-setup:
   runs-on: ubuntu-latest
   steps:
     - name: Setup Python 
       uses: actions/setup-python@v5.6.0
       with:
         java-version: '3.13'
        
     - name: print python version
       run: echo python --version
