name: variable

on: 
  workflow_dispatch
env:
  MY_VAR: workflow
jobs:
 variables:
     env:
      MY_VAR: jobs
     steps:
       - name: print
         run: echo ' ${{env.MY_VAR}}'
         env:
          MY_VAR: steps
  
